version: '3.9'

services:
    boilerplate:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/app
            - /app/node_modules
        ports:
            - 3000:3000

